"""
File: config_generator.py
Description: YAML configuration file generation (flat structure)
Author: Arjun Li
Created: 2026-04-16
Last Modified: 2026-04-17
Related modules: setup_wizard.py, config.py, paths.py
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

import yaml

from src.paths import PathRegistry, get_config_save_path


class NoAnchorDumper(yaml.SafeDumper):
    """Custom YAML Dumper that disables anchors/aliases."""

    def ignore_aliases(self, data):
        return True


def sanitize_project_name(name: str) -> str:
    """Sanitize project name for safe file naming."""
    if not name:
        return ""
    sanitized = name.replace(" ", "_")
    sanitized = re.sub(r"[^\w\-]", "", sanitized)
    return sanitized


def generate_config_yaml(
    project_name: str,
    paths: list[str],
    extensions: list[str],
    exclude_subdirs: list[str],
    global_excludes: list[str],
) -> str:
    """Generate flat YAML config file content."""
    header = "# zh-context-scanner project configuration\n"
    header += f"# Generated by Setup Wizard on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

    config_data = {
        "project_name": project_name,
        "paths": paths,
        "extensions": sorted(set(extensions)),
        "exclude_subdirs": sorted(set(exclude_subdirs)),
        "global_excludes": global_excludes,
    }

    yaml_content = yaml.dump(config_data, default_flow_style=False, sort_keys=False, Dumper=NoAnchorDumper)
    return header + yaml_content


def save_config_file(
    project_name: str,
    paths: list[str],
    extensions: list[str],
    exclude_subdirs: list[str],
    global_excludes: list[str],
    path_registry: PathRegistry,
) -> Path:
    """Generate and save config file to config/Project_Config.yaml."""
    sanitized_name = sanitize_project_name(project_name)
    if not sanitized_name:
        sanitized_name = "Project"

    config_content = generate_config_yaml(
        sanitized_name, paths, extensions, exclude_subdirs, global_excludes
    )
    config_path = get_config_save_path(path_registry)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content, encoding="utf-8")

    return config_path


def resolve_path(path_str: str) -> str:
    """Resolve path string to absolute POSIX path."""
    return Path(path_str).resolve().as_posix()
