"""
File: config_generator.py
Description: YAML configuration file generation and saving
Author: Arjun Li
Created: 2026-04-16
Last Modified: 2026-04-16
Related modules: setup_wizard.py, config.py, paths.py
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

import yaml

from src.config import ScanTarget
from src.paths import PathRegistry, get_config_save_path


class NoAnchorDumper(yaml.SafeDumper):
    """Custom YAML Dumper that disables anchors/aliases."""

    def ignore_aliases(self, data):
        return True


def sanitize_project_name(name: str) -> str:
    """Sanitize project name for safe file naming.

    - Replace spaces with underscores
    - Remove special characters (keep alphanumeric, underscore, hyphen)
    """
    if not name:
        return ""
    sanitized = name.replace(" ", "_")
    sanitized = re.sub(r"[^\w\-]", "", sanitized)
    return sanitized


def generate_config_yaml(
    project_name: str,
    scan_targets: list[ScanTarget],
    global_excludes: list[str],
) -> str:
    """Generate YAML config file content.

    Args:
        project_name: Project name for display
        scan_targets: List of ScanTarget objects
        global_excludes: Global exclude patterns

    Returns:
        YAML string content
    """
    header = "# zh-context-scanner project configuration\n"
    header += f"# Generated by Setup Wizard on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    header += "# Tip: You can manually add more exclude directories in this file\n\n"

    config_data = {
        "project_name": project_name,
        "scan_targets": [
            {
                "path": target.path,
                "extensions": target.extensions,
                "exclude_subdirs": target.exclude_subdirs,
            }
            for target in scan_targets
        ],
        "global_excludes": global_excludes,
    }

    yaml_content = yaml.dump(config_data, default_flow_style=False, sort_keys=False, Dumper=NoAnchorDumper)
    return header + yaml_content


def save_config_file(
    project_name: str,
    scan_targets: list[ScanTarget],
    global_excludes: list[str],
    path_registry: PathRegistry,
) -> Path:
    """Generate and save config file to appropriate directory.

    Args:
        project_name: Project name (will be sanitized for filename)
        scan_targets: List of ScanTarget objects
        global_excludes: Global exclude patterns
        path_registry: Path registry for determining save location

    Returns:
        Path to saved config file
    """
    sanitized_name = sanitize_project_name(project_name)
    if not sanitized_name:
        sanitized_name = "Project"

    config_content = generate_config_yaml(sanitized_name, scan_targets, global_excludes)
    config_path = get_config_save_path(sanitized_name, path_registry)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content, encoding="utf-8")

    return config_path


def create_scan_target(
    path_str: str,
    extensions: list[str],
    exclude_subdirs: list[str],
) -> ScanTarget:
    """Create a ScanTarget from user input.

    Args:
        path_str: Path string (will be converted to absolute path)
        extensions: File extensions to scan
        exclude_subdirs: Subdirectories to exclude

    Returns:
        ScanTarget object with absolute path
    """
    path = Path(path_str).resolve()
    path_str_abs = path.as_posix()

    return ScanTarget(
        path=path_str_abs,
        extensions=list(sorted(set(extensions))),
        exclude_subdirs=list(sorted(set(exclude_subdirs))),
    )
